# Essential Netlify configuration for Next.js DNSBunch
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://api2.dnsbunch.com"
  NEXT_PUBLIC_API_TIMEOUT = "30000"
  NODE_ENV = "production"

# API Proxy to backend
[[redirects]]
  from = "/api/*"
  to = "https://api2.dnsbunch.com/api/:splat"
  status = 200
  force = true
