# Essential Netlify configuration for Next.js DNSBunch
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://api2.dnsbunch.com"

# API Proxy Configuration
[[redirects]]
  from = "/api/*"
  to = "https://api2.dnsbunch.com/api/:splat"
  status = 200
  force = true

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
