#!/usr/bin/env python3
"""Content blocks for Phase 1 feature docs - used by apply_feature_docs.py."""
from __future__ import annotations

# Each entry: relative path under features/, then section overrides

TOOLS: dict[str, dict] = {
    "email/spf-checker.md": {
        "title": "SPF Checker",
        "tool_id": "spf_checker",
        "summary": "Look up SPF TXT at the domain apex, parse mechanisms, and report validity and common misconfigurations.",
        "problem": "Senders need a fast SPF validation without running full DNS health.",
        "in_scope": "TXT lookup for SPF record; parse `v=spf1`; count DNS lookups (warn >10); display mechanisms and modifiers.",
        "out_scope": "Sending test mail; DMARC/DKIM combined report (link to other tools).",
        "anon_flow": "Enter domain → Run → see SPF record, pass/warn/fail, mechanism list.",
        "logged_flow": "Same; optional save to history (Phase 2).",
        "architecture": "Python `backend/tools/spf_checker/` - DNS TXT only; register in tool registry. May reuse TXT helpers from dns_checker later.",
        "api": "POST `/api/tools/spf_checker` body `{ \"domain\": \"example.com\" }` - see [API.md](../../API.md#planned-internal-tools-and-bff).",
        "ui": "Template **T2**, route `/tools/spf-checker` - shadcn `Input`, `Button`, `Table`, `Alert` ([PAGE_TEMPLATES.md](../../ux/PAGE_TEMPLATES.md#t2--generic-tool-page)).",
        "limits": "Same IP rate limits as DNS health; max one domain per run.",
        "acceptance": [
            "Valid SPF record parsed and displayed",
            "Missing SPF reported clearly",
            "Too many DNS lookups flagged as warning",
        ],
    },
    "email/dkim-checker.md": {
        "title": "DKIM Checker",
        "tool_id": "dkim_checker",
        "summary": "Query DKIM TXT for a selectable selector (default `default`) at `{selector}._domainkey.{domain}`.",
        "problem": "Operators need to verify DKIM publication without manual dig.",
        "in_scope": "Selector input + domain; TXT fetch; show public key metadata and record validity.",
        "out_scope": "Signing mail; automatic selector discovery across all selectors.",
        "anon_flow": "Enter domain and selector → Run → DKIM record or not found.",
        "logged_flow": "Same.",
        "architecture": "Python `backend/tools/dkim_checker/`; DNS TXT.",
        "api": "POST `/api/tools/dkim_checker` `{ \"domain\", \"selector\"? }`.",
        "ui": "Template **T2**, `/tools/dkim-checker` - selector `Input` + domain.",
        "limits": "Rate limits per IP; validate domain/selector charset.",
        "acceptance": ["Record shown when present", "Invalid selector rejected client-side", "Clear not-found state"],
    },
    "email/dmarc-checker.md": {
        "title": "DMARC Checker",
        "tool_id": "dmarc_checker",
        "summary": "Query `_dmarc.{domain}` TXT, parse policy (none/quarantine/reject), alignment, and rua/ruf.",
        "problem": "High SEO demand for DMARC validation; operators need policy at a glance.",
        "in_scope": "TXT at `_dmarc`; parse tags p, sp, adkim, aspf, rua, ruf, pct.",
        "out_scope": "Aggregate report ingestion; mailbox verification for rua.",
        "anon_flow": "Enter domain → Run → policy table and raw record.",
        "logged_flow": "Same.",
        "architecture": "Python `backend/tools/dmarc_checker/` or extract from dns_checker DMARC check.",
        "api": "POST `/api/tools/dmarc_checker` `{ \"domain\" }`.",
        "ui": "Template **T2**, `/tools/dmarc-checker`.",
        "limits": "Standard IP limits.",
        "acceptance": ["Policy p= displayed", "rua/ruf URIs listed when present", "Missing DMARC shows actionable message"],
    },
    "email/mx-lookup.md": {
        "title": "MX Lookup",
        "tool_id": "mx_lookup",
        "summary": "List MX records with priorities; optional basic reachability hint (DNS only v1).",
        "problem": "Quick MX inspection separate from full health report.",
        "in_scope": "MX RRset sorted by preference; target hostnames.",
        "out_scope": "SMTP banner test (use smtp-test tool).",
        "anon_flow": "Enter domain → MX table.",
        "logged_flow": "Same.",
        "architecture": "Python `backend/tools/mx_lookup/`; dnspython.",
        "api": "POST `/api/tools/mx_lookup` `{ \"domain\" }`.",
        "ui": "Template **T2**, `/tools/mx-lookup`.",
        "limits": "Rate limits per IP.",
        "acceptance": ["All MX rows shown with priority", "No MX case handled"],
    },
    "email/smtp-test.md": {
        "title": "SMTP Test",
        "tool_id": "smtp_test",
        "summary": "Connect to MX on port 25 (or specified host), read banner, report TLS/support basics where safe.",
        "problem": "Verify mail server responsiveness without sending mail.",
        "in_scope": "TCP connect, EHLO, banner capture, timeout handling.",
        "out_scope": "Auth login; sending DATA; open relay full test (abuse risk).",
        "anon_flow": "Enter domain or host → Run → connection result and banner text.",
        "logged_flow": "Same.",
        "architecture": "Python asyncio SMTP client; strict timeouts; no message send.",
        "api": "POST `/api/tools/smtp_test` `{ \"domain\" | \"host\" }`.",
        "ui": "Template **T2**, `/tools/smtp-test`.",
        "limits": "Low concurrency per IP; short timeouts; block private IP targets.",
        "acceptance": ["Banner displayed on success", "Timeout errors user-friendly", "Does not send email"],
    },
    "email/dnsbl-blacklist.md": {
        "title": "DNSBL Lookup",
        "tool_id": "dnsbl_lookup",
        "summary": "Query common DNS blocklists for an IP or domain-derived IP (A record).",
        "problem": "Deliverability troubleshooting requires multi-RBL checks.",
        "in_scope": "Configurable small set of RBLs (e.g. zen.spamhaus.org); listed/not listed.",
        "out_scope": "Delisting requests; commercial RBL API keys.",
        "anon_flow": "Enter IP or domain → table of RBL results.",
        "logged_flow": "Same.",
        "architecture": "Python DNS queries to RBL zones; reverse IP encoding.",
        "api": "POST `/api/tools/dnsbl_lookup` `{ \"ip\" | \"domain\" }`.",
        "ui": "Template **T2**, `/tools/dnsbl-lookup`.",
        "limits": "Cap RBL count per run; rate limit; respect RBL provider terms.",
        "acceptance": ["Each RBL row shows listed/clean/error", "Invalid IP rejected"],
    },
    "website/ssl-inspector.md": {
        "title": "SSL Inspector",
        "tool_id": "ssl_inspector",
        "summary": "TLS handshake to host:443; certificate subject, issuer, validity dates, chain issues.",
        "problem": "Quick cert expiry and name mismatch checks for admins.",
        "in_scope": "Connect TLS; parse cert; SAN/CN vs input host.",
        "out_scope": "Full vulnerability scan; client cert auth.",
        "anon_flow": "Enter hostname → cert details table.",
        "logged_flow": "Same.",
        "architecture": "Python ssl/socket; SSRF rules [ARCHITECTURE §20](../../ARCHITECTURE.md).",
        "api": "POST `/api/tools/ssl_inspector` `{ \"host\" }`.",
        "ui": "Template **T2**, `/tools/ssl-inspector`.",
        "limits": "Block private/reserved IPs; timeout 15s.",
        "acceptance": ["Expiry date shown", "Hostname mismatch warning", "Connection failures explained"],
    },
    "website/http-headers.md": {
        "title": "HTTP Headers",
        "tool_id": "http_headers",
        "summary": "GET URL (HTTPS default), display response headers with security headers highlighted.",
        "problem": "Inspect caching, HSTS, CSP, and related headers quickly.",
        "in_scope": "Single GET; header list; highlight HSTS, CSP, X-Frame-Options, etc.",
        "out_scope": "Full site crawl; POST body testing.",
        "anon_flow": "Enter URL → header table with highlights.",
        "logged_flow": "Same.",
        "architecture": "Python httpx with redirects cap; BFF SSRF validation.",
        "api": "POST `/api/tools/http_headers` `{ \"url\" }`.",
        "ui": "Template **T2**, `/tools/http-headers`.",
        "limits": "SSRF deny list; max redirects 5; timeout 15s.",
        "acceptance": ["Status code shown", "Security headers section populated", "Invalid URL rejected"],
    },
    "website/redirect-chain.md": {
        "title": "Redirect Chain",
        "tool_id": "redirect_chain",
        "summary": "Follow redirects (GET), list each hop status, Location, and final URL.",
        "problem": "Debug redirect loops and HTTP→HTTPS chains.",
        "in_scope": "Up to N hops (e.g. 10); method GET.",
        "out_scope": "JavaScript redirects.",
        "anon_flow": "Enter URL → hop table.",
        "logged_flow": "Same.",
        "architecture": "Python httpx follow redirects manually for logging each hop.",
        "api": "POST `/api/tools/redirect_chain` `{ \"url\" }`.",
        "ui": "Template **T2**, `/tools/redirect-chain`.",
        "limits": "SSRF rules; max hops.",
        "acceptance": ["Each hop listed", "Loop detected message", "Final URL shown"],
    },
    "website/http-status.md": {
        "title": "HTTP Status",
        "tool_id": "http_status",
        "summary": "HEAD/GET URL; report status code, timing, and final URL after redirects.",
        "problem": "Simple up/down and status code check.",
        "in_scope": "Single URL; status + latency ms.",
        "out_scope": "Global uptime monitoring (Phase 3).",
        "anon_flow": "Enter URL → status badge and timing.",
        "logged_flow": "Same.",
        "architecture": "Python httpx; SSRF gate.",
        "api": "POST `/api/tools/http_status` `{ \"url\" }`.",
        "ui": "Template **T2**, `/tools/http-status`.",
        "limits": "SSRF; timeout.",
        "acceptance": ["Status code accurate", "Timeout handled"],
    },
    "domain/whois-lookup.md": {
        "title": "WHOIS Lookup",
        "tool_id": "whois_lookup",
        "summary": "WHOIS query for domain; registrar, dates, nameservers (parser-dependent).",
        "problem": "Registration context without leaving DNSBunch.",
        "in_scope": "WHOIS text or structured fields where library supports.",
        "out_scope": "Bulk WHOIS; legal WHOIS for all TLDs guaranteed.",
        "anon_flow": "Enter domain → WHOIS fields panel.",
        "logged_flow": "Same.",
        "architecture": "Python whois library; rate limit heavily.",
        "api": "POST `/api/tools/whois_lookup` `{ \"domain\" }`.",
        "ui": "Template **T2**, `/tools/whois-lookup`.",
        "limits": "Strict rate limits; cache responses short TTL optional.",
        "acceptance": ["Key fields shown when available", "Rate limit message on 429"],
    },
    "domain/domain-expiry.md": {
        "title": "Domain Expiry",
        "tool_id": "domain_expiry",
        "summary": "Extract expiry date from WHOIS/RDAP; days until expiration.",
        "problem": "Renewal reminders start with knowing expiry.",
        "in_scope": "Expiry date + countdown.",
        "out_scope": "Registrar API renew; alerts (Phase 3 monitoring).",
        "anon_flow": "Enter domain → expiry date and days left.",
        "logged_flow": "Same.",
        "architecture": "Reuse WHOIS/RDAP layer from whois tool.",
        "api": "POST `/api/tools/domain_expiry` `{ \"domain\" }`.",
        "ui": "Template **T2**, `/tools/domain-expiry`.",
        "limits": "WHOIS rate limits.",
        "acceptance": ["Expiry displayed or unknown explained", "Past expiry flagged warn"],
    },
    "domain/dns-propagation.md": {
        "title": "DNS Propagation",
        "tool_id": "dns_propagation",
        "summary": "Query A/AAAA/NS (selectable) against multiple public resolvers; show agreement map.",
        "problem": "See if DNS changes have propagated globally.",
        "in_scope": "Fixed resolver list; record type + name input.",
        "out_scope": "Custom resolver input from user (abuse); continuous monitoring.",
        "anon_flow": "Enter name + type → resolver result grid.",
        "logged_flow": "Same.",
        "architecture": "Python async DNS to multiple resolvers.",
        "api": "POST `/api/tools/dns_propagation` `{ \"name\", \"type\" }`.",
        "ui": "Template **T2**, `/tools/dns-propagation`.",
        "limits": "Cap resolver count; rate limit.",
        "acceptance": ["Each resolver row shows answers or error", "Mismatch highlighted"],
    },
    "domain/dns-history.md": {
        "title": "DNS History",
        "tool_id": "dns_history",
        "summary": "Show historical DNS record snapshots for a domain when data source available (Pro-oriented).",
        "problem": "Troubleshoot what changed after incidents.",
        "in_scope": "UI for timeline/table of past records; v1 may use third-party API or stub with Pro gate.",
        "out_scope": "Authoritative long-term archive operated by DNSBunch day one.",
        "anon_flow": "Free tier: limited preview or message to sign in.",
        "logged_flow": "Pro: full history views.",
        "architecture": "Next + Python; external data provider TBD; store queries in DB Phase 2+.",
        "api": "POST `/api/tools/dns_history` - entitlement checked Phase 3.",
        "ui": "Template **T2**, `/tools/dns-history` - timeline `Table`; access pro per metadata.",
        "limits": "Pro quota; no scraping without license.",
        "acceptance": ["Access gate matches access: pro", "Empty history explained"],
    },
}
